backend:
  name: test-repo

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    label_singular: Post
    folder: content/blog
    create: true
    delete: true
    extension: markdown
    format: frontmatter
    slug: "{{slug}}"
    preview_path: "blog/{{filename}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description, widget: text }
      - { name: date, label: Publication Date, widget: datetime }
      - { name: updated, label: Update Date, widget: datetime }
      - name: image
        label: Featured Image
        widget: object
        summary: "{{fields.src}}"
        fields:
          - { name: src, label: Image source, widget: image }
          - { name: alt, label: Alt text, widget: string }
          - {
              name: credit,
              label: Author of the image,
              widget: string,
              required: false,
            }
      - {
          name: tags,
          label: Tags,
          widget: select,
          multiple: true,
          options:
            [
              "Web Development",
              "Design",
              "Computer Science",
              "Data Science",
              "Mathematics",
            ],
          default: ["Computer Science"],
          min: 1,
          max: 4,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
